# Generated by Django 4.2.3 on 2023-09-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='std',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
