# Generated by Django 4.2.3 on 2023-09-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_students_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
