# Generated by Django 4.2.3 on 2023-09-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='std',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
